// Package swagger provides the Swagger documentation for the GNyx API.
// @title       GNyx API
// @version     0.0.1
// @description Backend modular API para o GNyx. (Powered by Kubex Ecosystem)
// @termsOfService  https://github.com/kubex-ecosystem/gnyx/terms
// @contact.name   GNyx API Support
// @contact.url    https://github.com/kubex-ecosystem/gnyx
// @contact.email  ti@kubex.world
// @host      localhost:8080
// @BasePath  /
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Forneça "Bearer <token>"
// @externalDocs.description  OpenAPI
// @externalDocs.url          https://swagger.io/resources/open-api/
// Package swagger provides the Swagger documentation for the GNyx API.
// package main
package swagger

import (
	"net"
	"os"

	"github.com/gin-gonic/gin"
	"github.com/kubex-ecosystem/gnyx/internal/config"
	kbxMod "github.com/kubex-ecosystem/gnyx/internal/module/kbx"
	router "github.com/kubex-ecosystem/gnyx/internal/runtime/gateway"

	// docs "github.com/kubex-ecosystem/gnyx/docs" // docs is generated by Swag CLI
	services "github.com/kubex-ecosystem/gnyx/internal/dsclient/adapters"
	kbx "github.com/kubex-ecosystem/kbx"
	kbxGet "github.com/kubex-ecosystem/kbx/get"
	kbxTypes "github.com/kubex-ecosystem/kbx/types"
	gl "github.com/kubex-ecosystem/logz"
	swaggerfiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/swaggo/swag/example/basic/docs"
)

func SwaggerMain(dbService services.Service[any], _ error) {
	// Initialize logger
	gl.Log("info", "Initializing Swagger...")

	serverConfig := &config.ServerConfig{
		SrvConfig: kbx.SrvConfig{
			Runtime: kbxTypes.SrvRuntimeParams{
				Host: "localhost",
				Port: "8080",
				Bind: net.JoinHostPort("localhost", "8080"),
			},
			Files: kbxTypes.SrvFilesParams{
				EnvFile:         os.ExpandEnv(kbxGet.EnvOr("KUBEX_GNYX_ENV_FILE", "./.env")),
				DBConfigFile:    os.ExpandEnv(kbxGet.EnvOr("KUBEX_DOMUS_CONFIG_FILE", "./config/db_config.yaml")),
				ProvidersConfig: os.ExpandEnv(kbxGet.EnvOr("KUBEX_GNYX_PROVIDERS_CONFIG_PATH", kbxMod.DefaultProvidersConfig)),
			},
			Basic: kbxTypes.SrvBasicParams{
				Debug:          kbxGet.EnvOrType("KUBEX_GNYX_DEBUG_MODE", false),
				ReleaseMode:    kbxGet.EnvOrType("KUBEX_GNYX_RELEASE_MODE", false),
				IsConfidential: kbxGet.EnvOrType("KUBEX_GNYX_CONFIDENTIAL_MODE", false),
				CORSEnabled:    kbxGet.EnvOrType("KUBEX_GNYX_ENABLE_CORS", true),
				UIDisabled:     kbxGet.EnvOrType("KUBEX_GNYX_DISABLE_UI", false),
			},
		},
	}

	// Initialize router
	rtr, err := router.NewServer(
		serverConfig,
	)

	if err != nil {
		gl.Log("fatal", "Failed to initialize router:", err)
		return
	}

	// Initialize Swagger
	ginSwagger.WrapHandler(swaggerfiles.Handler,
		ginSwagger.URL("http://localhost:8080/swagger/doc.json"),
		ginSwagger.DefaultModelsExpandDepth(-1))

	// Set up Swagger UI
	//router.GetEngine().GET("/swagger/*any", ginSwagger.WrapHandler(swaggerfiles.Handler))

	secureProperties := make(map[string]bool)
	secureProperties["secure"] = false
	secureProperties["validateAndSanitize"] = false
	secureProperties["validateAndSanitizeBody"] = false

	// Initialize routes
	// router.GetDefaultRouteMap(rtr)

	// Set up routes
	rtX := gin.New()
	rtX.MaxMultipartMemory = 8 << 20 // 8 MiB
	// rtX.Use(gin.Logger("github.com/kubex-ecosystem/gnyx"))
	rtX.Use(gin.ErrorLogger())
	rtX.Use(gin.Recovery())
	rtX.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerfiles.Handler))

	// rtr.SetEngine(rtX)
	// rtr.AddRoute(http.MethodGet, "/swagger/*any", nil, ginSwagger.WrapHandler(swaggerfiles.Handler), secureProperties)
	// rtr.AddDefaultRoutes()

	// Set up CORS
	// err = router.SecureServerInit(rtr.GetEngine(), net.JoinHostPort("localhost", "8080"))
	// if err != nil {
	// 	gl.Log("fatal", "Failed to initialize CORS:", err)
	// 	return
	// }

	// Start server
	gl.Log("info", "GNyx API Server starting...")
	gl.Log("info", "📚 Swagger docs available at: http://localhost:8080/swagger/index.html")
	gl.Log("info", "🔍 API endpoints at: http://localhost:8080/api/v1")

	docs.SwaggerInfo.Host = "localhost:8080"
	docs.SwaggerInfo.Title = "GNyx API"

	if err := rtr.Start(); err != nil {
		gl.Log("fatal", "Failed to start server:", err)
	}
}

func main() {
	// dbService, err := services.NewDBService(context.Background(), nil, nil)
	SwaggerMain(nil, nil)
}
